// Auto-generated by uinet-codegen. Do not edit.
import { uinet } from "@uinet/sdk";
import { SampleProxy } from "./sample.js";

export const sample = new SampleProxy(uinet);

export * from "./sample.js";
