// Auto-generated by uinet-codegen. Do not edit.
import type { UINetClient } from "@uinet/sdk";

export interface EchoArgs {
  text: string;
  count?: number | null;
}

export interface EchoResult {
  text: string;
  tags: string[];
  mood: "happy" | "neutral" | "sad";
}

export class SampleProxy {
  constructor(private client: UINetClient) {}

  echo(args: EchoArgs): Promise<EchoResult> {
    return this.client.invoke("sample", "echo", args);
  }
}
