using System.Text.Json;
using Vidra.CodeGen;

if (args.Length < 1 || args[0] != "generate")
{
    Console.Error.WriteLine(
        "Usage: vidra-codegen generate --assembly <paths...> --output <dir> [--scope core|app] [--check]");
    return 1;
}

var assemblies = new List<string>();
string outputDir = ".";
string sdkImport = "@vidra-dev/sdk";
string scope = "app";
var checkOnly = false;

for (var i = 1; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--assembly" or "-a":
            i++;
            while (i < args.Length && !args[i].StartsWith('-'))
            {
                assemblies.Add(args[i]);
                i++;
            }
            i--;
            break;
        case "--output" or "-o":
            i++;
            if (i < args.Length) outputDir = args[i];
            break;
        case "--sdk-import":
            i++;
            if (i < args.Length) sdkImport = args[i];
            break;
        case "--scope":
            i++;
            if (i < args.Length) scope = args[i].ToLowerInvariant();
            break;
        case "--check":
            checkOnly = true;
            break;
    }
}

if (assemblies.Count == 0)
{
    Console.Error.WriteLine("Error: at least one --assembly path is required.");
    return 1;
}
if (scope is not ("core" or "app"))
{
    Console.Error.WriteLine("Error: --scope must be 'core' or 'app'.");
    return 1;
}

// Scan assemblies
var scanner = new AssemblyScanner(assemblies.ToArray());
var manifest = scanner.Scan(assemblies.ToArray());

Console.WriteLine($"Found {manifest.Contracts.Count} contract(s):");
foreach (var (name, contract) in manifest.Contracts)
    Console.WriteLine(
        $"  {name} ({contract.NativeMethods.Count} native, {contract.Events.Count} events, {contract.JsMethods.Count} JS)");

var manifestJson = JsonSerializer.Serialize(manifest, new JsonSerializerOptions
{
    WriteIndented = true,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
}) + Environment.NewLine;

var emitter = new TypeScriptEmitter();
var outputs = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["manifest.json"] = manifestJson,
};
foreach (var (contractName, contract) in manifest.Contracts)
    outputs[$"{contractName}.ts"] = emitter.EmitContract(contractName, contract, sdkImport);

outputs["index.ts"] = emitter.EmitBarrel(manifest, sdkImport, scope);

if (checkOnly)
{
    var stale = outputs.Any(output =>
    {
        var path = Path.Combine(outputDir, output.Key);
        return !File.Exists(path)
               || !string.Equals(File.ReadAllText(path), output.Value, StringComparison.Ordinal);
    });
    if (stale)
    {
        Console.Error.WriteLine("Generated bridge contracts are stale. Run vidra-codegen generate.");
        return 2;
    }
    Console.WriteLine("Generated bridge contracts are current.");
    return 0;
}

Directory.CreateDirectory(outputDir);
foreach (var output in outputs)
{
    var path = Path.Combine(outputDir, output.Key);
    if (!File.Exists(path) || !string.Equals(File.ReadAllText(path), output.Value, StringComparison.Ordinal))
    {
        File.WriteAllText(path, output.Value);
        Console.WriteLine($"Wrote {path}");
    }
}

var expectedFiles = outputs.Keys.ToHashSet(StringComparer.OrdinalIgnoreCase);
foreach (var path in Directory.GetFiles(outputDir, "*.ts"))
{
    if (expectedFiles.Contains(Path.GetFileName(path)))
        continue;
    if (File.ReadLines(path).FirstOrDefault() == "// Auto-generated by vidra-codegen. Do not edit.")
    {
        File.Delete(path);
        Console.WriteLine($"Removed stale {path}");
    }
}

Console.WriteLine("Done.");
return 0;
