using System.Text;

namespace Vidra.CodeGen;

/// <summary>
/// Generates TypeScript proxy classes and type definitions from a <see cref="Manifest"/>.
/// </summary>
public sealed class TypeScriptEmitter
{
    /// <summary>
    /// Emit a .ts proxy file for a single module.
    /// </summary>
    /// <param name="sdkImportPath">Import path for the SDK, e.g. "../index.js" or "@vidra-dev/sdk".</param>
    public string EmitModule(string moduleName, ModuleManifest module, string sdkImportPath = "@vidra-dev/sdk")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by vidra-codegen. Do not edit.");
        sb.AppendLine($"import type {{ VidraClient }} from \"{sdkImportPath}\";");
        sb.AppendLine();

        // Collect all named types to emit as interfaces
        var namedTypes = new Dictionary<string, TypeRef>();
        foreach (var (_, method) in module.Methods)
        {
            CollectNamedTypes(method.Params, namedTypes);
            CollectNamedTypes(method.Returns, namedTypes);
        }

        foreach (var (name, typeRef) in namedTypes.OrderBy(kv => kv.Key))
        {
            sb.AppendLine($"export interface {name} {{");
            if (typeRef.Fields is not null)
            {
                foreach (var (fieldName, fieldType) in typeRef.Fields)
                {
                    var optional = fieldType.Kind == "nullable" ? "?" : "";
                    sb.AppendLine($"  {fieldName}{optional}: {TypeRefToTs(fieldType)};");
                }
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Proxy class
        var className = ToPascalCase(moduleName) + "Proxy";
        sb.AppendLine($"export class {className} {{");
        sb.AppendLine("  constructor(private client: VidraClient) {}");

        foreach (var (methodName, method) in module.Methods)
        {
            sb.AppendLine();
            var returnTs = method.Returns is not null ? TypeRefToTs(method.Returns) : "void";
            var paramTs = method.Params is not null ? $"args: {TypeRefToTs(method.Params)}" : "";
            var invokePayload = method.Params is not null ? ", args" : "";

            sb.AppendLine($"  {methodName}({paramTs}): Promise<{returnTs}> {{");
            sb.AppendLine($"    return this.client.invoke(\"{moduleName}\", \"{methodName}\"{invokePayload});");
            sb.AppendLine("  }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emit a barrel index.ts that creates pre-bound module instances from the default client.
    /// </summary>
    /// <param name="sdkImportPath">Import path for the SDK, e.g. "../index.js" or "@vidra-dev/sdk".</param>
    public string EmitBarrel(Manifest manifest, string sdkImportPath = "@vidra-dev/sdk")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by vidra-codegen. Do not edit.");
        sb.AppendLine($"import {{ vidra }} from \"{sdkImportPath}\";");

        foreach (var (moduleName, _) in manifest.Modules.OrderBy(kv => kv.Key))
        {
            var className = ToPascalCase(moduleName) + "Proxy";
            sb.AppendLine($"import {{ {className} }} from \"./{moduleName}.js\";");
        }

        sb.AppendLine();

        foreach (var (moduleName, _) in manifest.Modules.OrderBy(kv => kv.Key))
        {
            var className = ToPascalCase(moduleName) + "Proxy";
            sb.AppendLine($"export const {moduleName} = new {className}(vidra);");
        }

        sb.AppendLine();

        // Re-export all types for convenience
        foreach (var (moduleName, _) in manifest.Modules.OrderBy(kv => kv.Key))
        {
            sb.AppendLine($"export * from \"./{moduleName}.js\";");
        }

        return sb.ToString();
    }

    private string TypeRefToTs(TypeRef typeRef)
    {
        return typeRef.Kind switch
        {
            "primitive" => typeRef.TsType!,
            "nullable" => $"{TypeRefToTs(typeRef.Element!)} | null",
            "array" => $"{ArrayElementToTs(typeRef.Element!)}[]",
            "enum" => string.Join(" | ", typeRef.Values!.Select(v => $"\"{ToCamelCase(v)}\"")),
            "object" when typeRef.Name is not null => typeRef.Name,
            "object" when typeRef.Fields is not null => InlineObject(typeRef.Fields),
            "record" => typeRef.Name ?? "unknown",
            _ => "unknown",
        };
    }

    /// <summary>
    /// Renders an array's element type, wrapping union-producing elements
    /// (enum string-unions, nullable <c>T | null</c>) in parentheses so the
    /// trailing <c>[]</c> applies to the whole union rather than its last
    /// member (e.g. <c>("a" | "b")[]</c>, not the invalid <c>"a" | "b"[]</c>).
    /// </summary>
    private string ArrayElementToTs(TypeRef element)
    {
        var ts = TypeRefToTs(element);
        return element.Kind is "enum" or "nullable" ? $"({ts})" : ts;
    }

    private string InlineObject(Dictionary<string, TypeRef> fields)
    {
        var parts = fields.Select(kv =>
        {
            var optional = kv.Value.Kind == "nullable" ? "?" : "";
            return $"{kv.Key}{optional}: {TypeRefToTs(kv.Value)}";
        });
        return $"{{ {string.Join("; ", parts)}; }}";
    }

    private void CollectNamedTypes(TypeRef? typeRef, Dictionary<string, TypeRef> collected)
    {
        if (typeRef is null) return;

        if (typeRef.Kind == "object" && typeRef.Name is not null && typeRef.Fields is not null)
        {
            collected.TryAdd(typeRef.Name, typeRef);
            foreach (var field in typeRef.Fields.Values)
                CollectNamedTypes(field, collected);
        }

        if (typeRef.Kind == "array" && typeRef.Element is not null)
            CollectNamedTypes(typeRef.Element, collected);

        if (typeRef.Kind == "nullable" && typeRef.Element is not null)
            CollectNamedTypes(typeRef.Element, collected);
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
