import crypto from "node:crypto";
import path from "node:path";
import fs from "fs-extra";
import { createJiti } from "jiti";
// TypeScript 7's package root no longer exposes the compiler API. This runtime
// dependency deliberately pins the stable TypeScript 5 AST surface used here.
import ts from "typescript-compiler-api";
import type { UpdateConfig } from "./update-config.js";

export const VIDRA_CONFIG_FILE = "vidra.config.ts";
export const BRIDGE_POLICY_FILE = "vidra-bridge-policy.json";

const NATIVE_METHOD_TOKEN = "vidra.native-method";
const EVENT_TOKEN = "vidra.event";
const FILESYSTEM_ROOT_TOKEN = "vidra.filesystem-root";
const ROOT_NAMES = new Set(["appData", "cache", "documents", "downloads"]);

export type VidraCommand =
  | "build"
  | "bundle"
  | "dev"
  | "doctor"
  | "run"
  | "updates";

export interface VidraConfigContext {
  command: VidraCommand;
  mode: "development" | "production";
  target: "macos" | "windows" | "android" | null;
}

export interface BridgeMemberIdentity {
  contract: string;
  member: string;
}

export interface NormalizedFilesystemGrant {
  root: "appData" | "cache" | "documents" | "downloads";
  relativePath?: string;
  methods: BridgeMemberIdentity[];
}

export interface BridgePolicyDocument {
  version: 1;
  nativeMethods: BridgeMemberIdentity[];
  events: BridgeMemberIdentity[];
  filesystem: NormalizedFilesystemGrant[];
}

export interface LoadedVidraConfig {
  updates: UpdateConfig | null;
  bridgePolicy: BridgePolicyDocument;
  bridgePolicyText: string;
  accessFingerprint: string;
}

export class VidraConfigError extends Error {}

export interface GeneratedWriteResult {
  path: string;
  changed: boolean;
}

const EMPTY_POLICY: BridgePolicyDocument = {
  version: 1,
  nativeMethods: [],
  events: [],
  filesystem: [],
};

export const loadVidraConfig = async (
  projectRoot: string,
  context: VidraConfigContext,
): Promise<LoadedVidraConfig> => {
  const configPath = path.join(projectRoot, VIDRA_CONFIG_FILE);
  if (!fs.existsSync(configPath)) {
    return finalizeConfig(null, EMPTY_POLICY);
  }

  let exported: unknown;
  try {
    const jiti = createJiti(import.meta.url, {
      moduleCache: false,
      fsCache: false,
      interopDefault: true,
    });
    exported = await jiti.import(configPath, { default: true });
  } catch (error) {
    throw new VidraConfigError(
      `${VIDRA_CONFIG_FILE}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  if (typeof exported === "function") {
    exported = await exported(context);
  }

  const config = objectAt(exported, VIDRA_CONFIG_FILE);
  assertOnlyKeys(config, ["bridge", "updates"], VIDRA_CONFIG_FILE);
  const bridgePolicy = readBridgePolicy(config.bridge);
  const updates = readUpdates(config.updates);
  return finalizeConfig(updates, bridgePolicy);
};

export const serializeBridgePolicy = (
  policy: BridgePolicyDocument,
): string => `${JSON.stringify(policy, null, 2)}\n`;

export const writeBridgePolicy = (
  hostDir: string,
  loaded: LoadedVidraConfig,
): GeneratedWriteResult => {
  const output = path.join(hostDir, "Resources", "Raw", BRIDGE_POLICY_FILE);
  return writeIfChanged(output, loaded.bridgePolicyText);
};

export const writeFrontendAccessFingerprint = (
  uiDir: string,
  fingerprint: string,
): GeneratedWriteResult => {
  const output = path.join(uiDir, "src", "generated", "vidra-access-policy.ts");
  return writeIfChanged(
    output,
    [
      "// Generated by the Vidra CLI. Do not edit.",
      'import { vidra } from "@vidra-dev/sdk";',
      "",
      `vidra.registerExpectedAccessFingerprint(${JSON.stringify(fingerprint)});`,
      "",
    ].join("\n"),
  );
};

/**
 * Rewrites only the `updates` property of a direct defineConfig({ ... }) call.
 * Other config shapes remain valid to load, but are intentionally not mutated
 * because preserving their semantics would require executing user code.
 */
export const writeVidraUpdateConfig = (
  projectRoot: string,
  updates: UpdateConfig,
): void => {
  const configPath = path.join(projectRoot, VIDRA_CONFIG_FILE);
  const source = fs.readFileSync(configPath, "utf8");
  const file = ts.createSourceFile(
    configPath,
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const exportAssignment = file.statements.find(ts.isExportAssignment);
  const expression = exportAssignment?.expression;
  if (
    !expression ||
    !ts.isCallExpression(expression) ||
    !ts.isIdentifier(expression.expression) ||
    expression.expression.text !== "defineConfig" ||
    expression.arguments.length !== 1 ||
    !ts.isObjectLiteralExpression(expression.arguments[0])
  ) {
    throw new VidraConfigError(
      `${VIDRA_CONFIG_FILE}: updates can be edited automatically only when the default export is defineConfig({ ... })`,
    );
  }

  const configObject = expression.arguments[0];
  const rendered = renderProperty("updates", updates, "  ");
  const property = configObject.properties.find(
    (entry) => propertyName(entry.name) === "updates",
  );

  let next: string;
  if (property) {
    next =
      source.slice(0, property.getStart(file)) +
      rendered +
      source.slice(property.end);
  } else {
    const insertion = configObject.getEnd() - 1;
    const separator = configObject.properties.length > 0 ? "," : "";
    next =
      source.slice(0, insertion).trimEnd() +
      `${separator}\n${rendered}\n` +
      source.slice(insertion);
  }
  fs.writeFileSync(configPath, next);
};

const finalizeConfig = (
  updates: UpdateConfig | null,
  policy: BridgePolicyDocument,
): LoadedVidraConfig => {
  const bridgePolicyText = serializeBridgePolicy(policy);
  return {
    updates,
    bridgePolicy: policy,
    bridgePolicyText,
    accessFingerprint: crypto
      .createHash("sha256")
      .update(bridgePolicyText, "utf8")
      .digest("hex"),
  };
};

const readBridgePolicy = (value: unknown): BridgePolicyDocument => {
  if (value === undefined) return EMPTY_POLICY;
  const bridge = objectAt(value, `${VIDRA_CONFIG_FILE}.bridge`);
  assertOnlyKeys(
    bridge,
    ["allow", "events", "filesystem"],
    `${VIDRA_CONFIG_FILE}.bridge`,
  );

  const nativeMethods = readMemberTokens(
    bridge.allow,
    NATIVE_METHOD_TOKEN,
    `${VIDRA_CONFIG_FILE}.bridge.allow`,
  );
  if (nativeMethods.some((method) => method.contract === "filesystem")) {
    throw new VidraConfigError(
      `${VIDRA_CONFIG_FILE}.bridge.allow cannot grant filesystem methods without a resource scope; use bridge.filesystem`,
    );
  }
  const events = readMemberTokens(
    bridge.events,
    EVENT_TOKEN,
    `${VIDRA_CONFIG_FILE}.bridge.events`,
  );
  const filesystem = readFilesystemGrants(bridge.filesystem);

  for (const grant of filesystem) {
    for (const method of grant.methods) {
      if (method.contract !== "filesystem") {
        throw new VidraConfigError(
          `${VIDRA_CONFIG_FILE}.bridge.filesystem accepts only native.filesystem methods`,
        );
      }
    }
  }

  return {
    version: 1,
    nativeMethods: sortMembers(dedupeMembers(nativeMethods)),
    events: sortMembers(dedupeMembers(events)),
    filesystem: normalizeFilesystemGrants(filesystem),
  };
};

const readFilesystemGrants = (
  value: unknown,
): NormalizedFilesystemGrant[] => {
  if (value === undefined) return [];
  if (!Array.isArray(value)) {
    throw new VidraConfigError(
      `${VIDRA_CONFIG_FILE}.bridge.filesystem must be an array`,
    );
  }

  return value.map((entry, index) => {
    const location = `${VIDRA_CONFIG_FILE}.bridge.filesystem[${index}]`;
    const grant = objectAt(entry, location);
    assertOnlyKeys(grant, ["root", "allow"], location);
    const root = objectAt(grant.root, `${location}.root`);
    if (
      root.kind !== FILESYSTEM_ROOT_TOKEN ||
      typeof root.name !== "string" ||
      !ROOT_NAMES.has(root.name)
    ) {
      throw new VidraConfigError(`${location}.root is not a filesystem root token`);
    }

    const relativePath = readRelativePath(root.relativePath, `${location}.root`);
    const methods = readMemberTokens(
      grant.allow,
      NATIVE_METHOD_TOKEN,
      `${location}.allow`,
    );
    if (methods.length === 0) {
      throw new VidraConfigError(`${location}.allow must not be empty`);
    }

    return {
      root: root.name as NormalizedFilesystemGrant["root"],
      ...(relativePath ? { relativePath } : {}),
      methods: sortMembers(dedupeMembers(methods)),
    };
  });
};

const readRelativePath = (
  value: unknown,
  location: string,
): string | undefined => {
  if (value === undefined || value === "") return undefined;
  if (typeof value !== "string" || path.isAbsolute(value)) {
    throw new VidraConfigError(`${location}.relativePath must be relative`);
  }

  const normalized = value.replaceAll("\\", "/").replace(/^\.\/+/, "");
  const segments = normalized.split("/");
  if (
    normalized.length === 0 ||
    segments.some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    throw new VidraConfigError(
      `${location}.relativePath must not contain empty, "." or ".." segments`,
    );
  }
  return normalized;
};

const readMemberTokens = (
  value: unknown,
  kind: string,
  location: string,
): BridgeMemberIdentity[] => {
  if (value === undefined) return [];
  if (!Array.isArray(value)) {
    throw new VidraConfigError(`${location} must be an array`);
  }

  return value.map((entry, index) => {
    const token = objectAt(entry, `${location}[${index}]`);
    if (
      token.kind !== kind ||
      typeof token.contract !== "string" ||
      token.contract.length === 0 ||
      typeof token.member !== "string" ||
      token.member.length === 0
    ) {
      throw new VidraConfigError(
        `${location}[${index}] is not a valid generated token`,
      );
    }
    return { contract: token.contract, member: token.member };
  });
};

const readUpdates = (value: unknown): UpdateConfig | null => {
  if (value === undefined) return null;
  const updates = objectAt(value, `${VIDRA_CONFIG_FILE}.updates`);
  assertOnlyKeys(
    updates,
    ["feed", "publicKeys", "enabled"],
    `${VIDRA_CONFIG_FILE}.updates`,
  );

  const result: UpdateConfig = {};
  if (updates.enabled !== undefined && typeof updates.enabled !== "boolean") {
    throw new VidraConfigError(
      `${VIDRA_CONFIG_FILE}.updates.enabled must be a boolean`,
    );
  }
  if (typeof updates.enabled === "boolean") result.enabled = updates.enabled;

  if (typeof updates.feed === "string") {
    if (updates.feed.trim()) result.feed = updates.feed.trim();
  } else if (updates.feed !== undefined) {
    const feed = objectAt(updates.feed, `${VIDRA_CONFIG_FILE}.updates.feed`);
    assertOnlyKeys(feed, ["web", "app"], `${VIDRA_CONFIG_FILE}.updates.feed`);
    if (feed.web !== undefined && typeof feed.web !== "string") {
      throw new VidraConfigError(
        `${VIDRA_CONFIG_FILE}.updates.feed.web must be a string`,
      );
    }
    if (feed.app !== undefined && typeof feed.app !== "string") {
      throw new VidraConfigError(
        `${VIDRA_CONFIG_FILE}.updates.feed.app must be a string`,
      );
    }
    const split: { web?: string; app?: string } = {};
    if (typeof feed.web === "string" && feed.web.trim()) split.web = feed.web.trim();
    if (typeof feed.app === "string" && feed.app.trim()) split.app = feed.app.trim();
    if (Object.keys(split).length > 0) result.feed = split;
  }

  if (updates.publicKeys !== undefined) {
    if (
      !Array.isArray(updates.publicKeys) ||
      !updates.publicKeys.every((key) => typeof key === "string")
    ) {
      throw new VidraConfigError(
        `${VIDRA_CONFIG_FILE}.updates.publicKeys must be an array of strings`,
      );
    }
    const keys = updates.publicKeys
      .map((key) => key.trim())
      .filter((key) => key.length > 0);
    if (keys.length > 0) result.publicKeys = keys;
  }

  return Object.keys(result).length > 0 ? result : null;
};

const objectAt = (value: unknown, location: string): Record<string, unknown> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new VidraConfigError(`${location} must be an object`);
  }
  return value as Record<string, unknown>;
};

const assertOnlyKeys = (
  value: Record<string, unknown>,
  allowed: readonly string[],
  location: string,
): void => {
  const unknown = Object.keys(value).filter((key) => !allowed.includes(key));
  if (unknown.length > 0) {
    throw new VidraConfigError(
      `${location}: unknown ${unknown.length === 1 ? "key" : "keys"} ${unknown.join(", ")}`,
    );
  }
};

const dedupeMembers = (
  values: BridgeMemberIdentity[],
): BridgeMemberIdentity[] => {
  const seen = new Set<string>();
  return values.filter((value) => {
    const key = `${value.contract}\0${value.member}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
};

const sortMembers = (
  values: BridgeMemberIdentity[],
): BridgeMemberIdentity[] =>
  values.sort(
    (left, right) =>
      compareOrdinal(left.contract, right.contract) ||
      compareOrdinal(left.member, right.member),
  );

const normalizeFilesystemGrants = (
  grants: NormalizedFilesystemGrant[],
): NormalizedFilesystemGrant[] => {
  const merged = new Map<string, NormalizedFilesystemGrant>();
  for (const grant of grants) {
    const key = `${grant.root}\0${grant.relativePath ?? ""}`;
    const current = merged.get(key);
    if (!current) {
      merged.set(key, { ...grant, methods: [...grant.methods] });
      continue;
    }
    current.methods = sortMembers(
      dedupeMembers([...current.methods, ...grant.methods]),
    );
  }
  return [...merged.values()].sort((left, right) =>
    compareOrdinal(
      `${left.root}/${left.relativePath ?? ""}`,
      `${right.root}/${right.relativePath ?? ""}`,
    ),
  );
};

const compareOrdinal = (left: string, right: string): number =>
  left < right ? -1 : left > right ? 1 : 0;

const propertyName = (name: ts.PropertyName | undefined): string | null => {
  if (!name) return null;
  if (ts.isIdentifier(name) || ts.isStringLiteral(name)) return name.text;
  return null;
};

const renderProperty = (
  name: string,
  value: unknown,
  indent: string,
): string => {
  const json = JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => {
      const withoutQuotedKey = line.replace(
        /^(\s*)"([A-Za-z_$][\w$]*)":/,
        "$1$2:",
      );
      return index === 0 ? withoutQuotedKey : indent + withoutQuotedKey;
    })
    .join("\n");
  return `${indent}${name}: ${json}`;
};

const writeIfChanged = (
  output: string,
  contents: string,
): GeneratedWriteResult => {
  if (fs.existsSync(output) && fs.readFileSync(output, "utf8") === contents) {
    return { path: output, changed: false };
  }

  fs.ensureDirSync(path.dirname(output));
  fs.writeFileSync(output, contents, "utf8");
  return { path: output, changed: true };
};
