// Auto-generated by vidra-codegen. Do not edit.
import { vidra } from "@vidra-dev/sdk";
import { DialogHandlers } from "./dialog.js";
import { SampleProxy } from "./sample.js";

vidra.registerGeneratedManifest("app", "27e349abb4ce23ff0500bf892d747efa30083410f477dd37e1d4d14e370b5029");

export const dialogHandlers = new DialogHandlers(vidra);
export const sample = new SampleProxy(vidra);

export * from "./dialog.js";
export * from "./sample.js";
