// Auto-generated by vidra-codegen. Do not edit.
import { vidra } from "@vidra-dev/sdk";
import { SampleProxy } from "./sample.js";

export const sample = new SampleProxy(vidra);

export * from "./sample.js";
