// Auto-generated by vidra-codegen. Do not edit.
import type { VidraClient } from "@vidra-dev/sdk";

export interface EchoArgs {
  text: string;
  count?: number | null;
}

export interface EchoResult {
  text: string;
  tags: string[];
  mood: "happy" | "neutral" | "sad";
  moods: ("happy" | "neutral" | "sad")[];
  note?: string | null;
}

export class SampleProxy {
  constructor(private client: VidraClient) {}

  echo(args: EchoArgs): Promise<EchoResult> {
    return this.client.invoke("sample", "echo", args);
  }
}
